preimage:
  sample_dir: "sample_dir"
  result_dir: "result_dir"
  over_approx: False
  under_approx: True
  threshold: 0.75
  label: 0
#general:
#  device: cuda
model:
  onnx_path: "model_dir/simple_cnn_cifar10.onnx"
specification:
  type: 'bound'
  robustness_type: "verified-acc"
data:
  dataset: CIFAR
  mean: [ 0.4914, 0.4822, 0.4465 ]
  std: [ 0.2023, 0.1994, 0.2010 ]
solver:
  batch_size: 64
bab:
  branching:
    method: "preimg"
    input_split:
      enable: True
